// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHistoryDetail = "HistoryDetail"

// HistoryDetail mapped from table <HistoryDetail>
type HistoryDetail struct {
	ID          int32     `gorm:"column:ID;primaryKey;default:nextval('"HistoryDetail_ID_seq"'::regclass);comment:NGS generated" json:"ID"` // NGS generated
	HistoryID   int32     `gorm:"column:HistoryID;not null;comment:NGS generated" json:"HistoryID"`                                         // NGS generated
	Species     string    `gorm:"column:species;not null;default:''::character varying;comment:NGS generated" json:"species"`               // NGS generated
	TotalColony int32     `gorm:"column:totalColony;not null;comment:NGS generated" json:"totalColony"`                                     // NGS generated
	CreatedAt   time.Time `gorm:"column:createdAt;comment:NGS generated" json:"createdAt"`                                                  // NGS generated
	UpdatedAt   time.Time `gorm:"column:updatedAt;comment:NGS generated" json:"updatedAt"`                                                  // NGS generated
	DeletedAt   time.Time `gorm:"column:deletedAt;comment:NGS generated" json:"deletedAt"`                                                  // NGS generated
}

// TableName HistoryDetail's table name
func (*HistoryDetail) TableName() string {
	return TableNameHistoryDetail
}
