// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHistory = "History"

// History mapped from table <History>
type History struct {
	//ID             int32     `gorm:"column:ID;primaryKey;default:nextval('"History_ID_seq"'::regclass);comment:NGS generated" json:"ID"`       // NGS generated
	ID             int32     `gorm:"column:ID;primaryKey;comment:NGS generated" json:"ID"`                                                     // NGS generated
	SampleName     string    `gorm:"column:sampleName;not null;default:''::character varying;comment:NGS generated" json:"sampleName"`         // NGS generated
	UserID         int32     `gorm:"column:UserID;not null;comment:NGS generated" json:"UserID"`                                               // NGS generated
	LocalFileImage string    `gorm:"column:localFileImage;not null;default:''::character varying;comment:NGS generated" json:"localFileImage"` // NGS generated
	CreatedAt      time.Time `gorm:"column:createdAt;comment:NGS generated" json:"createdAt"`                                                  // NGS generated
	UpdatedAt      time.Time `gorm:"column:updatedAt;comment:NGS generated" json:"updatedAt"`                                                  // NGS generated
	DeletedAt      time.Time `gorm:"column:deletedAt;comment:NGS generated" json:"deletedAt"`                                                  // NGS generated
}

// TableName History's table name
func (*History) TableName() string {
	return TableNameHistory
}
