// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "User"

// User mapped from table <User>
type User struct {
	ID                    int32     `gorm:"column:ID;primaryKey;default:nextval('"User_ID_seq"'::regclass);comment:NGS generated" json:"ID"` // NGS generated
	Email                 string    `gorm:"column:email;not null;default:''::character varying;comment:NGS generated" json:"email"`          // NGS generated
	Password              string    `gorm:"column:password;not null;default:''::character varying;comment:NGS generated" json:"password"`    // NGS generated
	ForgottenPasswordTime time.Time `gorm:"column:forgottenPasswordTime;comment:NGS generated" json:"forgottenPasswordTime"`                 // NGS generated
	ForgottenPasswordCode string    `gorm:"column:forgottenPasswordCode;comment:NGS generated" json:"forgottenPasswordCode"`                 // NGS generated
	LastAccess            time.Time `gorm:"column:lastAccess;comment:NGS generated" json:"lastAccess"`                                       // NGS generated
	FullName              string    `gorm:"column:fullName;not null;default:''::character varying;comment:NGS generated" json:"fullName"`    // NGS generated
	CreatedAt             time.Time `gorm:"column:createdAt;comment:NGS generated" json:"createdAt"`                                         // NGS generated
	UpdatedAt             time.Time `gorm:"column:updatedAt;comment:NGS generated" json:"updatedAt"`                                         // NGS generated
	DeletedAt             time.Time `gorm:"column:deletedAt;comment:NGS generated" json:"deletedAt"`                                         // NGS generated
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
