// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"bacteriapp/core"
	"bacteriapp/services"
)

import (
	_ "context"
	_ "fmt"
	_ "gopkg.in/yaml.v2"
	_ "io/ioutil"
	_ "os"
	_ "time"
)

// Injectors from wire.go:

func InitializeServiceProvider(c *core.Config) services.ServiceProvider {
	dbAdapter := NewDBAdapter(c)
	userMapper := NewUserMapper(dbAdapter)
	mailerService := NewMailerService(c)
	userService := NewUserService(userMapper, mailerService)
	appService := NewAppService(c, mailerService, userService)
	serviceProvider := NewServiceProvider(userService, mailerService, appService)
	return serviceProvider
}
